### ISSUE TITLE
Working Example

### ISSUE THREAD

**Issue by Rob-ModernAnalytics** [pfmooney/node-ldapjs-mangle-proxy#1]
Hi,

I am accessing the AD Group object and need to convert the Group SID to the standard string version of a SID below:

S-1-5-21-28854893-1799698802-1116685130-102498

It looks like your code does this but I can't seem to find a combination that works for me.  I have an AD object called "group" and I need to convert the group.objectSid property to the format above.

Any help you can provide would be greatly appreciated!

Thanks,

Rob

**Comment by Rob-ModernAnalytics** [comment]
Hi - I finally got this to produce a sid that is formatted properly.  However, the sid that I get does not match the sid that is produced by Windows PowerShell.  

The sid that I get from your utility is:
S-1-5-21-33376877-1799698802-1123894090-195915

while the sid that I get from PowerShell for the same group object is:
S-1-5-21-28854893-1799698802-1116685130-146502

Strange that two of the subauth values are corrrect but the other two are not.

Does anyone have an explanation for this?

Thanks,

Rob

**Comment by Rob-ModernAnalytics** [comment]
Here is the code I'm using:

var buffer = new Buffer(group.objectSid, 'binary');
var sid = new ObjectSid();
sid.fromBinary(buffer);
console.log('result', sid.toString());

Thanks,

Rob

**Comment by pfmooney** [comment]
I would suggest checking to ensure that you're acting on the raw `Buffer` representation of the `objectSid` field, rather than one that may have undergone conversion to a UTF-8 string.

**Comment by Rob-ModernAnalytics** [comment]
Patrick,

Thanks for the quick response. I thought I tried intercepting the data in the active directory module and I couldn't get it to run the callback code. I will try again tomorrow.

Any thoughts on how else I might get to the raw buffer?

Thanks,

Rob

On Jun 26, 2017, at 6:08 PM, Patrick Mooney <notifications@github.com<mailto:notifications@github.com>> wrote:


I would suggest checking to ensure that you're acting on the raw Buffer representation of the objectSid field, rather than one that may have undergone conversion to a UTF-8 string.

**Comment by pfmooney** [comment]
If you're speaking of node-activedirectory, it calls entry.object on search results, which does render out the raw fields to UTF-8 strings.  Attempting the objectSid translation on that data will yield incorrect results.

**Comment by Rob-ModernAnalytics** [comment]
Patrick,

As per the example in the node-activedirectory docs I created a custom entry parser to capture the raw objectSid and the translation to a string matches exactly what I need.

Thank you for all your hard work and quick response!

Rob
